### ISSUE TITLE
Spacing Bug

### ISSUE THREAD

**Issue by dinouse** [michaelmelita1/11CamMin#1]
First of all, Love your work! Secondly, there was a problem with your tweaks. Just checkout the picture. The zoom is working well! Im using [[NewCam]] + [[11CamMin]]![Uploading 79896122...]()

**Comment by michaelmelita1** [comment]
Your picture didn’t upload. I don’t provide support for that tweak as it hooks the same code that mine does. Please choose one or the other or compile my tweak 11Cam

**Comment by michaelmelita1** [comment]
(Thank you for your support tho)
